CREATE TABLE cadastro(
cod_membro SERIAL PRIMARY KEY,
nome VARCHAR(50),
rg NUMERIC(8),
cpf NUMERIC(11),
orgao_expedidor TEXT,
sexo VARCHAR(10),
pai VARCHAR(50),
mae VARCHAR(50),
naturalidade VARCHAR(30),
uf_identidade VARCHAR(10),
pais TEXT,
cep NUMERIC(8),
logradouro VARCHAR(50),
numero NUMERIC(8),
complemento VARCHAR(25),
bairro VARCHAR(40),
cidade VARCHAR(30),
uf_endereco VARCHAR(10),
telefone NUMERIC(13),
data_nasc DATE,
estado_civil VARCHAR(25),
nome_conjuge VARCHAR(30),
profissao VARCHAR(30),
escolaridade VARCHAR(30),
data_batismo DATE,
batizado_esp_santo VARCHAR(10),
entrada_rol_membros DATE,
congregacao VARCHAR(25),
funcao VARCHAR(15),
origem VARCHAR(15),
situacao VARCHAR(20),
igreja_cidade TEXT
)